version: 0.1

phases:
  build:
    commands:
      - yarn install
      - yarn run webpack
artifacts:
  files:
    - index.html
    - favicon.ico
    - resume.pdf
    - styles/*
    - images/*
    - dist/bundle.js
